theme = "mod-kiera"
baseURL = "/" # always include the trailing slash
languageCode = "en-us"
title = "ejelome"

pygmentsCodeFences = true

disqusShortname = "ejelome"        # Disqus shortname
googleAnalytics = "UA-144170438-1" # Google Analytics ID

[author]
    name = "Emmanuel-Jelome Fonseca"             # Author name
    github = "ejelome"                           # GitHub username
    youtube = "channel/UCgqy7fcflZb5hhfLAUmlc5g" # YouTube channel
    linkedin = "ejelome"                         # LinkedIn username

[params]
    domain = "ejelome.com"
    tagline = "Research, Design and Development"
    description = "Research, Design and Development"

home = [ "HTML", "RSS", "JSON"]
menu = "main"
meta = "false"
