#+TITLE: Interaction Design Basics
#+DATE: 2019-07-28

#+HUGO_BASE_DIR: ../../
#+HUGO_TAGS: hci ixd
#+HUGO_CATEGORIES: Research Design

* Summary

  This is a re-interpretation of /*Interaction Design*/[fn:1] Basics from the /*HCI*/[fn:2] course of the /*IDF*/[fn:3] by /*Alan Dix*/[fn:4] .
  This solely focuses on lesson 2.
  #+HUGO: more

  -----

* Design

** What are we designing?

   For most people, the answer might obviously be an *interface* (visual, what is seen); but that's rather lacking as an answer.
   The answer is: we are designing an *interaction* (not just an *what it's* [interface], but also *what to do with it* [interaction]).

** The camera example

   Think of the camera:

   - What is a camera?
   - Why use a camera?

   It will rather be disappointing to think that a camera is all about how it looks (interface).
   A better thought about a camera is that it's about taking photographs (interaction).

   And a much deeper thought (emotion) is that, a camera is a device that's used to capture moments,
   and being able to collect these moments and keep them as memories to later on revisit.

** Interaction, not just interfaces

   And that's what we should design,
   like the camera, design is about:

   - a *series of actions* (view, click) to accomplish a goal (photographs)
   - *not just the immidiate interaction* --- it's the *whole flow* (overall use)

** Intervention not just artifacts

   It's also not just about the thing we are designing (*artifact*, e.g. camera),
   but also how the design can change things (*intervention*, e.g. how people will treat photos).

** What is a design?

   A design is *achieving a goal within constraints*.

   - Goal means *purpose* (who is it for and why would they need it)
   - Constraints mean *limitations* (time, budget, expertise, platform)

   To achieve a goal within constraints is about dealing with *trade-offs*.

   - It's *deciding between what we want and what we can really achieve*
   - Trade-offs are at the heart of working in a design

** Understand the materials

   - Computers (platforms, tools)
   - People (psychological, social, human error)
   - And how these two interacts (complementarity)

** Human error

   Human error is the typical excuse when people fail to use a design properly,
   but in reality, human error occurs as a result of a *poor design* ---
   *design errors* that did not took enough consideration
   the *human characteristics and limitations* that led to mistakes and even accidents.

   -----

* The design process

** The 5 Stages in Interaction Design

   The general flow of Interaction Design Process that revolves around a design process --- *from needs to fulfillment*.

** Step 1: Research

   The first step is conducting researches to find out *what users want and need*.
   If we do not know what users want and need, then how can we provide it?
   It's always easy to assume what users want and need but it just leads to further misunderstanding.

   Some approaches exists to gain a better understanding of users, such as:

   - Observation (look, watch)
   - Interviews (talk, ask)
   - See existing solutions (relevant things that they are already using)

** Step 2: Analysis

   Once a good understanding of users' wants and needs are achieved,
   comes analysis, which is to make sense of the understood information:

   - By /*task analysis*/[fn:5] that splits an action into smaller steps
   - Thru a /*scenario*/[fn:6] that express a specific need and how to achieve it

** Step 3: Design

   This is the main point of action in the design process where the design is actually being worked on
   --- the stage where:

   - *principles* (general rules) are applied
   - *guidelines* (rules for specific people and technology) are followed
   - *dialogues* (how users can interact with the design) are explored

**  Step 4: Prototype

   A *prototype* is sample of the design
   that gives the users an opportunity to *try it out*.
   A prototype allows us to have a real-world:

   - /*heuristics*/[fn:7] (design compliance with recognized *usability principles*)
   - /*cultural probe*/[fn:8] (fragmentary clues to inspire our imagination)
   - *technology probe* (see people's reaction on the new technology)

   *Remember: We never get it right the first time*, because:

   - No one can fully understand people
   - No one can fully understand situations

** Step 5: Implement and Deploy

   This is the stage where we bring up to life the design for the world to see.
   It's when users will use the design in their lives and where the real work begins in order to sustain the technology, namely:

   - Architecture (how it works together, e.g. people, systems, networks)
   - Infrastructure (components to facilitate the architecture)
   - Documentation (how to use the artifact)
   - Maintenance (how to maintain the artifact)
   - Help System (e.g. user assistance thru software)
   - Help Desk (e.g. customer support thru operators)
   - and seeing the actual intervention (*change*)

** The artifact

   All these steps of the design process were done to produce the artifact (*product*)
   and all the necessary steps that were executed to create the intervention (*change*).

** Learn what to prioritize

   Because of these many stages of the design process, how can one person do it all alone?
   The answer is: *one person can't* --- because constraints and trade-offs will eventually occur.

   And in the process, one will invest more on some areas while simplifying the rest, hence, the *compromise*.

   One will also find that *the most difficult thing is not finding or solving a problem,*
   *but deciding which of these problems to solve.* Due to limitations, all problems can't be solved at once.

   The irony is that, *a perfectly designed system is the result of a poor design process*.
   Because too much time have been spent on the design process and time was not spent efficiently.
   So unless the people involved are in a multi-million dollar business, they should *know when to stop*.

** Desire vs. Disaster

   And out of these problems begs the question, *what to prioritize?*
   The two major criterias of where to put an effort are:

   - *desire* (what make users want to use the product)
   - *disaster* (what make users stop using the product)

   The rule of thumb is --- fix the *disasters first*, then do the *desires later*.

   -----

* User Focus

** Know thy user

   As the most famous delphic maxims states, /*know thyself*/[fn:9].
   This is also true for users who will use the design.
   This perhaps, is the most important aspect in interaction design.

** Who are the users?

   - We are not the users (/*false consensus-effect*/[fn:10])
   - But we can be one of them
   - Talk to them (from informal to a formal way)
   - Watch them (observe: know what they say from what they really do)
   - Use our imagination (put ourselves in their shoes, *empathize*)

   Ironically, an expert can even be the worst person to know who the users are (/*curse of knowledge*/[fn:11]).

** Personas

   A persona is fictional representation of a user that will use the design.
   The richer the persona description, the more we'll think like the user.

** Cultural probes

   Cultural probes encultures us on users' way of life.
   It helps us get a realistic understanding of users' current situation.

** Technology probes

   Technology probes enables us to see people's reaction when presented to new technologies.
   It helps us to understand how these technologies can change people's way of life.

   -----

* Scenarios

  Like personas, scenarios are fictional stories of users that will use the design.
  But unlike personas, it focuses on users' *actions needed to achieve a certain goal*.

** Scenarios as walkthroughs

   Scenarios allow us to define walkthroughs that imagined users will act out, such as:

   - What users will see (visual, e.g. they see a button)
   - What users will do (behavior, e.g. they clicked that button)
   - What users are thinking (motive, e.g. why they clicked [expectations])

** Scenarios and its limitations

   While scenarios can provide a clearer picture of how users can possibly interact with the design,
   it has its own limitations, such that it ---

   - can't represent all the users (each user are unique)
   - can miss the unintended (it's linear and can't provide all scenarios)
   - needs to be based on real users to be factual and avoid assumptions
   - must use real personas to expose real problems and areas to improve

   -----

* Navigation

  The navigation defines how users can move between screens (desktop) or pages (web browsers, devices).
  It's the flow in the design that allow users to find their way around the system.

** Multiple levels of design

   There are four fundamental levels of a design, namely:

   | Level       | Web                        | Device                  | Example                       |
   |-------------+----------------------------+-------------------------+-------------------------------|
   | Widget      | Tag                        | Control                 | Menu, Button                  |
   | Screen      | Page                       | Layout                  | Layout, placement of Widgets  |
   | Navigation  | Structure                  | Modes                   | Linking one screen to another |
   | Environment | Web browser, other website | The World, other device | The platform (OS, other apps) |

** Design structures

   The design structure defines how each of the levels can fit together.

** The Local structure

   The local structure defines the *current* screen that users are at.
   It tells them where they currently are in the system (*they are somewhere*).

** Four golden rules

   There are four golden rules on the *local* structure that must be answered:

   | Question            | Answer      | Example             |
   |---------------------+-------------+---------------------|
   | Where they are?     | Scent       | Breadcrumbs         |
   | What can they do?   | Action      | Click a link        |
   | What will happen?   | Expectation | Go to the next page |
   | What have happened? | Outcome     | Now in that page    |

** Information scent

   /Peter Pirolli/[fn:12] and /Stuart Card/[fn:13], along with colleagues in /*Xerox PARC*/[fn:14], developed the /*information foraging*/[fn:15] theory.
   It's an analogy that like wild animals gathering food, humans do the same to gather information cues online.
   It's considered the most important concept that emerged in HCI research since 1993.

   Under this theory is the most important concept called /*information scent*/[fn:16].
   It states that, like animals that rely on scents to guide them finding a prey, so as humans rely on information cues.
   But as users get less useful information, the more likely they will stop going further and just move to another source.

   A rule of thumb regarding information scent is that *a good scent leads you straight to the goal*.
   Users have a goal in mind and it's our job to help them reach that goal as short and fast as possible.

** The Global structure

   The global structure defines the *relationships* of each screens that helps users to navigate throughout the whole system.

** Hierarchy structure

   This is the most common structure by which screens are organized by relevance.
   it's top-down, tree-like, one-to-many --- it's an *information-oriented* structure.

   The main advantage of this structure is that each part can clearly define its own function.
   A big disadvantage, however, is that the more the functions, the deeper (*depth*) it becomes.
   And the deeper users are in the system, the more difficult for them to *track* their location.

** Miller's Magical Number: Seven, Plus or Minus Two

   In 1956, Cognitive psychologist, /George A. Miller/[fn:17] of /Harvard University/[fn:18] published:
   /The Magical Number Seven, Plus or Minus Two/[fn:19],
   often referred to as /*Miller's law*/[fn:20] that states: *humans can only hold an average of 7 chunks in short-term memory*.

   This is typically misused in design, esp. suggesting the number of items in menus ---
   users do not really memorize the number of items in menus --- they *scan*.

   However, that's not to say that the number of items in a menu does not matter,
   in fact, if there are too much items in a menu (*breadth*), it becomes difficult to scan
   and if the menu has less items but is too deep (*depth*), it becomes difficult to track.

** Network structure

   This is an alternative structure by which screens are organized according to *dialogues*.
   It's not linear which lead users to different screens --- it's a *task-oriented* structure.

   The main advantage of this structure is its flexibility to organize screens depending on their context.
   A big disadvantage, on the other hand, is that it's more complicated because outcomes depend on choices.

** Between applications

   The overall user experience does not simply revolve in one application.
   The design does not end with just the local and global structures
   but also its functionalities to be consistent with other applications.

   An example is how we move information (e.g. /*cut, copy, and paste*/[fn:21] between applications.
   In terms of websites or web applications, going to and from external pages.
   A common way to maintain consistency is thru a /*style guide*/[fn:22] (e.g. /Apple/[fn:23]'s /Human Interface Guidelines/[fn:24]).

   -----

* Screen Design

  The screen design defines what users see on the screen --- one at a time.

** Basic principles

   1. Ask: What users want to do? (action)
   2. Think: What are they looking for? (expectation)
   3. Design: /*form follows function*/[fn:25] (appearance equals intention[fn:26])

** Screen elements

   There are a number of elements that can expose the functions of forms on a screen, such as:

   1. Grouping (*combine* related items)
   2. Order (*natural ordering* of items)
   3. Decoration (*emphasize* important items)
   4. Alignment (*readability* of items)
   5. Whitespace (*separation* of items)

** Affordances

   In his 1966 book, /The Senses Considered as Perceptual Systems/[fn:27], psychologist, /James J. Gibson/[fn:28],
   coined the term /*affordance*/[fn:29], that he later defined in his 1979 book, /The Ecological Approach to Visual Perception/[fn:30],
   which states that affordance *implies the complementarity of the animal and the environment.*

   In terms of design, affordances provide users with strong cues on how objects they see can operate.
   Objects are self-explanatory (*obvious*) and do not need further instructions on how to use them.

** Countries and cultures

   A product that wants to enter a global (international) market, requires understanding of varying cultures.
   Different users of different places and cultures wants their identity and practices to be respected.
   There are general design considerations when dealing with different countries and cultures, such as:

   1. Translation (*t9n* [translation]; one language to another)
   2. Localization (/*L10N*/[fn:31] [localization]; *locale-specific*, *culture-sensitive*)
   3. Internationalization (/*i18n*/[fn:32] [internationalization]; multiple countries)
   4. Globalization (*g11n* [globalization]; design with both *L10n* and *i18n*)

   -----

* Iteration and prototypes

  Iteration and prototypes allow us to test the effectiveness and learn in the design process up-front.
  Remember that *we can't make it right the first time*; hence, learn then improve things along the way.

** The prototype cycle

   1. Design (*transform* the abstract into concrete)
   2. Prototype (*preliminary* artifact of the design)
   3. Test (e.g. /*usability testing*/[fn:33] to evaluate thru *user testing*)
   4. Evaluate (*measure* and *learn* from the results)
   5. Refine (*iterate* and *improve* the design and fix problems)

   ... then decide, *it's good enough*, then ship it (*release*).
   And *good enough does not mean perfect*, but the start of the technology probe.

** The Local Maximum

   /The Local Maximum/[fn:34] is a phenomena by which a design can't get much better simply because it has reached its peek.
   Such that, starting with a dreadful design, and even fixing all of its problems, will still end up, dreadful.

   A better approach is to always start with a *better design* (*global maximum*) --- start somewhere better,
   and as such:

   1. begin with a *very good starting point*
   2. have a *better understanding* of:

      1. the problem
      2. the target users
      3. the technology being built
      4. and how to connect them together

* Footnotes

[fn:1] [[https://en.wikipedia.org/wiki/Interaction_design][Interaction Design]]
[fn:2] [[https://en.wikipedia.org/wiki/Human%25E2%2580%2593computer_interaction][Human–Computer Interaction]]
[fn:3] [[https://www.interaction-design.org][Interaction Design Foundation]]
[fn:4] [[https://alandix.com][Alan Dix]]
[fn:5] [[https://en.wikipedia.org/wiki/Task_analysis][Task analysis]]
[fn:6] [[https://en.wikipedia.org/wiki/Scenario_(computing)][Scenario]]
[fn:7] [[https://en.wikipedia.org/wiki/Heuristic_evaluation][Heuristic evaluation]]
[fn:8] [[https://en.wikipedia.org/wiki/Cultural_probe][Cultural probe]]
[Fn:9] [[https://en.wikipedia.org/wiki/Know_thyself][Know thyself]]
[fn:10] [[https://en.wikipedia.org/wiki/False_consensus_effect][False-consensus effect]]
[fn:11] [[https://en.wikipedia.org/wiki/Curse_of_knowledge][Curse of knowledge]]
[fn:12] [[http://www.peterpirolli.com][Peter Pirolli]]
[fn:13] [[https://web.archive.org/web/20070209223029/http://www2.parc.com/istl/projects/uir/people/stuart/stuart.htm][Stuart Card]]
[fn:14] [[https://en.wikipedia.org/wiki/PARC_(company)][Xerox PARC]]
[fn:15] [[https://en.wikipedia.org/wiki/Information_foraging][Information foraging]]
[fn:16] [[https://en.wikipedia.org/wiki/Information_foraging#Information_scent][Information scent]]
[fn:17] [[https://wikipedia.org/wiki/George_Armitage_Miller][George A. Miller]]
[fn:18] [[https://www.harvard.edu][Harvard University]]
[fn:19] [[https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two][The Magical Number Seven, Plus or Minus Two]]
[fn:20] [[https://en.wikipedia.org/wiki/Miller%2527s_law][Miller's law]]
[fn:21] [[https://en.wikipedia.org/wiki/Cut,_copy,_and_paste][Cut, copy, and paste]]
[fn:22] [[https://en.wikipedia.org/wiki/Style_guide][Style guide]]
[fn:23] [[https://www.apple.com][Apple]]
[fn:24] [[https://developer.apple.com/design/human-interface-guidelines][Human Interface Guidelines]]
[fn:25] [[https://en.wikipedia.org/wiki/Form_follows_function][Form follows function]]
[fn:26] [[https://wikipedia.org/wiki/Louis_Sullivan][Louis Sullivan]]
[fn:27] [[http://web.flu.cas.cz/scan/323542127.pdf][The Senses Considered as Perceptual Systems]]
[fn:28] [[https://wikipedia.org/wiki/James_J._Gibson][James J. Gibson]]
[fn:29] [[https://en.wikipedia.org/wiki/Affordance][Affordance]]
[fn:30] [[https://archive.org/stream/pdfy-u5hmFOvOM2Civ4Gz/THE+ECOLOGICAL+APPROACH+TO+VISUAL+PERCEPTION_djvu.txt][The Ecological Approach to Visual Perception]]
[fn:31] [[https://en.wikipedia.org/wiki/Language_localisation][Language localisation]]
[fn:32] [[https://en.wikipedia.org/wiki/Internationalization_and_localization][Internationalization and localization]]
[fn:33] [[https://en.wikipedia.org/wiki/Usability_testing][Usability_testing]]
[fn:34] [[https://52weeksofux.com/post/694598769/the-local-maximum][The Local Maximum]]
