#!/bin/bash
#
# Minify JSON files.
#
# Arguments:
#   ${1} Source directory
#   ${2} Output directory

# Require 2 arguments:
if [[ ${#} -ne 2 ]]; then
  printf "Error: Invalid number of arguments\n\tExpected '1' but got '${#}'\n"
  exit
fi

# Require input file:
if [[ ! -d ${1} ]]; then
  printf "Error: Invalid source directory\n\tDirectory '${1}' not found\n"
  exit
fi

FILE_EXTENSIONS=("json" "webmanifest")
EXTENSIONS=$(printf '%s\n' "$(IFS=,; printf '%s' "${FILE_EXTENSIONS[*]}")")

for file in ${1}/*; do
  for extension in ${FILE_EXTENSIONS[@]}; do
    if [[ ${file} == *.${extension} ]]; then
      filename=$(basename ${file})
      jq -c . < ${file} > ${2}/${filename}

      TIMESTAMP=$(date +%Y-%m-%d\ %H:%M:%S)
      echo "[${TIMESTAMP}] INFO jq -c . < ${file} > ${2}/${filename}"
    fi
  done
done
